### PR TITLE
Update costello-sig.html

### PR DESCRIPTION
**Pull request by clarissamgrayson**
Added Vivian Ho

### CODE REVIEW

**Review by MrMuzik — APPROVED** [review]
LGTM

**Comment by clarissamgrayson** [comment]
I'm not sure i got the code right first time. And need to know where to
drop the image for hosting. Didn't see a Img src folder

**Comment by MrMuzik** [comment]
@clarissamgrayson Yeah you are right, I shouldn't have approved that. The structure is correct but the content is incorrect.

**Comment by clarissamgrayson** [comment]
Yeah I needed to see it work, preview but I couldn't find the link for the
preview

**Pull request merged**
